name: jawara_pintar
description: Mobile application for Jawara Pintar system.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.1
  firebase_storage: 13.0.4
  cloudinary_public: ^0.21.0
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  go_router: ^16.2.4
  lucide_icons: ^0.257.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/